"https://gregishere.com/":
    type: upstream
    upstream: "app:http"
"https://gregsuehr.com/":
    type: upstream
    upstream: "app:http"
"https://getkatzen.com/":
    type: upstream
    upstream: "app:http"

"https://www.mulvaylitmas.com/":
  type: redirect
  to: "https://mulvaylitmas.com/"

"https://mulvaylitmas.com/":
  type: upstream
  upstream: "app:http"